### ISSUE TITLE
删除pv和pvc时不能自动删除chubaofs里的目录吗

### ISSUE THREAD

**Issue by zhanggok** [cubefs/cubefs-csi#46]
创建pvc后这chubaofs里创建了目录，但是删除pvc和pv后也没有服务器上也没有删除创建的目录。
已经设置reclaimPolicy: Delete
这nfs里设置
parameters:
  archiveOnDelete: "false"
就可以删除

这 https://github.com/chubaofs/chubaofs-csi/blob/master/deploy/storageclass-default.yaml 这里也没有看出那个参数跟nfs类似

**Comment by chengyu-l** [comment]
能贴一下csi controller的日志吗？
