### ISSUE TITLE
docker pull  unknown blob

### ISSUE THREAD

**Issue by ledrsnet** [cubefs/cubefs-csi#64]
(base) root@ubuntu:~# docker pull ghcr.io/cubefs/cfs-csi-driver:2.4.1.110.1
2.4.1.110.1: Pulling from cubefs/cfs-csi-driver
a8c7037c15e9: Pulling fs layer 
ee77564112b3: Pulling fs layer 
c9a8edccd926: Pulling fs layer 
8ad28c0cab2b: Pulling fs layer 
e7f6b46a46e9: Pulling fs layer 
3ae92f87a760: Pulling fs layer 
6d4b6ceb8d2a: Pulling fs layer 
dc9b4b510e80: Pulling fs layer 
error pulling image configuration: download failed after attempts=1: unknown blob

**Comment by Huweicai** [comment]
It seems that something wrong happens to the image, I'll rebuild it.

**Comment by Huweicai** [comment]
It's ok now.
