### ISSUE TITLE
is there a plan to support kubernetes 1.22+

### ISSUE THREAD

**Issue by iPenx** [cubefs/cubefs-csi#68]
Hi! 

I am going to use cubefs but the version of my kubernetes cluster is 1.22.5.
Could I ask is there a plan to support kubernetes 1.22+?

**Comment by Huweicai** [comment]
Hi, kubernetes 1.22 + was supported.

**Comment by Huweicai** [comment]
You can have a try.

**Comment by iPenx** [comment]
Thanks. Let me try.
