### ISSUE TITLE
batch create pvc vol failed

### ISSUE THREAD

**Issue by sz891016** [cubefs/cubefs-csi#92]
I use script to create pvc volume serially， when create finished,  some pvc status is pending.
All of the pvc volume can be see in cubefs volume list, but when you use **kebectl get pvc**  , you can see some vol status are pending.

**create pvc script:**
```
# /bin/sh
date
for i in {1..10};do
cat <<EOF | kubectl create -f -&
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cubefs-batch-pvc-qa-${i}
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: cfs-sc-with-consul-3.3
EOF
done
wait

echo "脚本执行完成"
```
pending pvc log
![image](https://github.com/cubefs/cubefs-csi/assets/26965250/eba12296-2025-48f3-8a78-10993fa4fb6e)

**Comment by heymingwei** [comment]
I will fix it
