### ISSUE TITLE
could you update this plugin a little bit, it not working on the latest k8s

### ISSUE THREAD

**Issue by Bmixo** [cubefs/cubefs-csi#98]
Prerequisite

Kubernetes 1.16.0
CSI spec version 1.1.0

is really old tested version

**Comment by heymingwei** [comment]
so what happened when plugin running? give some informations or give a screenshot would be better @Bmixo

**Comment by Bmixo** [comment]
@heymingwei 
i use the following command to install CSI plugin into my k8s system, and my k8s version is v1.26.4+k3s1, you can check the image below, the problem is the storage class did not work as except, yes i mean although i can create the storage class from the yaml file you provide in this project README file,but it just unable to mount the exist cubefs server in to container. **I thinks is issue is relate to the Provisioner list did not show this plugin.**  

```
$ kubectl apply -f deploy/csi-rbac.yaml
$ kubectl apply -f deploy/csi-controller-deployment.yaml
$ kubectl apply -f deploy/csi-node-daemonset.yaml
```

![image](https://github.com/cubefs/cubefs-csi/assets/25509024/69a08a45-6c50-4b06-9d04-3de5ec735e46)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/83a15aad-47e1-480c-b54f-c20ec17136df)

**Comment by heymingwei** [comment]
maybe you need to  create the csidriver resource, the yaml content is
```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.cubefs.com
spec:
  attachRequired: false
  podInfoOnMount: true
```
maybe you can find the provisioner after this step @Bmixo

**Comment by Bmixo** [comment]
1. when the cluster unable to create volume thought client-cli, this plugin still able to mount and create volume and use local-path this is un-acceptable
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/beebad3c-7088-4ab3-886c-6e7c83f25cf5)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/0bc9e056-6351-403b-b72c-485d06d209f2)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/f8568b51-b0b0-4aad-908f-dce8c2ed4b2e)

2.when cluster is available is working  
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/6f217fad-dc12-468e-af05-cf5a521c7688)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/8b8f4e7d-0fa2-4a46-a150-bca27469c901)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/ecb3dba6-b884-47c4-9e6d-dbaf36ad14e4)
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/49c62680-2ac9-4d5b-a49a-679796bffb5f)

**Comment by Bmixo** [comment]
1. when the cluster unable to create volume thought client-cli, this plugin still able to mount and create volume and use local-path i think this is an un-acceptable bug

2.when cluster is available this plugin is working
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/8df5368b-3dee-4e67-ae2d-fb4ea0f55c9e)


@heymingwei

**Comment by Bmixo** [comment]
![image](https://github.com/cubefs/cubefs-csi/assets/25509024/7982b8d1-8add-4743-9e1e-d4fa2bca34df)

**Comment by Bmixo** [comment]
close,i make a CSI plugin by myself.
